app/routes/auth.py
from flask import request, Blueprint, render_template, redirect, url_for, flash
from app.data import database, User
import hashlib
from flask_login import login_user, current_user

auth_bp = Blueprint("auth_bp", __name__)


@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("index_bp.index"))
    if request.method == "POST":
        if "" in request.form.values():
            flash("Пожалуйста, заполните все поля")
            return render_template("login.html")
        # Проверка на существование пользователя
        existing_user = database.users.find_one({"email": request.form["email"]})
        if existing_user:
            if (
                hashlib.sha256(
                    request.form["password"].encode()
                ).hexdigest()  # Проверка верности пароля с шифрованием
                == existing_user["h_password"]
            ):
                user = User(
                    existing_user["_id"],
                    existing_user["username"],
                    existing_user["collection_ids"],
                )
                login_user(user)
                return redirect(url_for("index_bp.index"))
        else:
            flash("Ошибка аутентификации")
            return render_template("login.html")
    return render_template("login.html")


@auth_bp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("index_bp.index"))
    if request.method == "POST":
        if "" in request.form.values():
            flash("Пожалуйста, заполните все поля")
            return render_template("register.html")
        elif request.form["password"] != request.form["password_repeat"]:
            flash("Неверный повтор пароля")
            return render_template("register.html")
        # Проверка на существование пользователя
        existing_user = database.users.find_one(
            {"username": request.form["username"]}
        ) or database.users.find_one({"email": request.form["email"]})
        if existing_user:
            if existing_user["email"] == request.form["email"]:
                flash("Этот адрес занят")
                return render_template("register.html")
            if existing_user["username"] == request.form["username"]:
                flash("Этот ник занят")
                return render_template("register.html")
        user = {
            "username": request.form["username"],
            "email": request.form["email"],
            "h_password": hashlib.sha256(
                request.form["password"].encode()
            ).hexdigest(),  # Шифрование пароля
            "collection_ids": [],
        }

        database.users.insert_one(user)
        flash("Успешная регистрация! Теперь вы можете войти в свой аккаунт.")
        return render_template("register.html")
    return render_template("register.html")

app/routes/collections.py
from flask import Blueprint, abort, request, flash, render_template, redirect
from bson import ObjectId
from app.data import database
from app.utils import allowed_file
from flask_login import login_required, current_user
import time, chardet
from app.metric import MetricsCollector
from werkzeug.utils import secure_filename
from app.handling import file_handling


collections_bp = Blueprint("collections_bp", __name__)


@collections_bp.route("/collections", methods=["GET", "POST"])
@login_required
def collections():
    if request.method == "POST":
        if "" in request.form.values():
            flash("Пожалуйста, введите имя коллекции")
        else:
            name = request.form["collection_name"].strip()
            existing_collection = database.collections.find_one(
                {"user_id": current_user.id, "name": name}
            )  # Ищем коллекции с айди текущего пользователя и с именем name...
            if existing_collection:
                flash(
                    "Данная коллекция уже существует"
                )  # ...выводим ошибку, если такая коллекция существует
            else:
                collection = {"user_id": current_user.id, "name": name, "doc_ids": []}
                insert_res = database.collections.insert_one(collection)
                database.users.update_one(
                    {"_id": ObjectId(current_user.id)},
                    {
                        "$push": {"collection_ids": insert_res.inserted_id}
                    },  # Добавляем в поле collection_ids id только что созданной колекции.
                )
                flash("Коллекция успешно создана!")

    user_collections = list(
        database.collections.find({"user_id": current_user.id})
    )  # Ищем все коллекции текущего пользователя, передавая их в шаблон
    return render_template("collections.html", collections=user_collections)


@collections_bp.route("/collections/<collection_id>/documents", methods=["GET", "POST"])
@login_required
def documents(collection_id: str):
    collection = database.collections.find_one({"_id": ObjectId(collection_id)})
    if not collection or collection["user_id"] != current_user.id:
        abort(403)  # Запрет, если происходит попытка получить доступ к чужим документам
    collection_documents = list(
        database.documents.find({"collection_id": ObjectId(collection_id)})
    )  # Сбор всех документов, с полем collection_id = collection_id
    return render_template(
        "documents.html", collection=collection, documents=collection_documents
    )


@collections_bp.route("/collections/<collection_id>/delete", methods=["GET", "POST"])
@login_required
def delete_collection(collection_id):
    collection = database.collections.find_one({"_id": ObjectId(collection_id)})
    if not collection or collection["user_id"] != current_user.id:
        abort(403)
    result = database.collections.delete_one(
        {"_id": ObjectId(collection_id), "user_id": current_user.id}
    )
    if result.deleted_count:
        flash("Коллекция удалена")
    else:
        flash("Коллекция не найдена")
    user_collections = list(database.collections.find({"user_id": current_user.id}))
    database.users.update_one(
        {"_id": ObjectId(current_user.id)},
        {"$pull": {"collection_ids": ObjectId(collection_id)}},
    )

    return render_template("collections.html", collections=user_collections)


@collections_bp.route("/collections/<collection_id>/upload", methods=["GET", "POST"])
@login_required
def upload(collection_id):
    metrics = MetricsCollector(database)
    collection = database.collections.find_one({"_id": ObjectId(collection_id)})
    if not collection or collection["user_id"] != current_user.id:
        abort(403)

    if request.method == "POST":
        if "file" not in request.files:
            flash("No file part")
            return redirect(request.url)
        file = request.files["file"]
        if file.filename == "":
            flash("No selected file")
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            raw_data = file.read()
            encoding = chardet.detect(raw_data)["encoding"]
            if encoding is None:
                encoding = "utf-8"
            content = raw_data.decode(encoding)
            start = time.time()
            words_data = file_handling(
                content, filename, collection_id, current_user.id
            )
            duration = round(time.time() - start, 3)
            metrics.register_file_processed(duration)
            return render_template(
                "upload.html",
                words=words_data,
                filename=filename,
                collection_name=collection["name"],
            )
        else:
            flash("Forbidden file extension")
            return redirect(request.url)

    return render_template("upload.html", collection_name=collection["name"])

app/templates/collections.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>Document Analyzer|Collections</title>
    </head>
    <body>
        <a href="{{ url_for('index_bp.index') }}">Домашняя страница</a>
        <h1>Мои коллекции</h1>
        
        <form method="POST" action="{{ url_for('collections_bp.collections') }}">
            <h2>Cоздать новую коллекцию</h2>
            {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <h3>{{ message }}</h3>
                {% endfor %}
            {% endif %}
            {% endwith %}
            <input type="text" name="collection_name" placeholder="Имя коллекции" required>

            <button type="submit">Создать</button>
        </form>
        <hr>
         {% if collections %}
        <h2>Список коллекций</h2>
        <table border="1">
            <tr>
                <th>Название</th>
                <th>Действия</th>
            </tr>
            {% for collection in collections %}
            <tr>
                <td>{{ collection.name }}</td>
                <td>
                    <a href = "{{ url_for('collections_bp.documents', collection_id=collection._id) }}" >Смотреть</a>
                    <a href="{{ url_for('collections_bp.upload', collection_id=collection._id) }}">Загрузить</a>
                    <a href="{{ url_for('collections_bp.delete_collection', collection_id=collection._id) }}">Удалить</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
    <p>У вас пока нет коллекций.</p>
    {% endif %}
    </body>
</html>

app/templates/documents.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>Document Analyzer|Documents</title>
    </head>
    <body>
        <a href="{{ url_for('index_bp.index') }}">Домашняя страница</a>
        <a href="{{ url_for('collections_bp.collections') }}">Мои коллекции</a>
        <h1>Документы коллекции {{ collection.name }}</h1>
        <hr>
         {% if documents %}
        <h2>Список документов</h2>
        <table border="1">
            <tr>
                <th>Название</th>
                <th>ID</th>
                <th>Действия</th>
            </tr>
            {% for document in documents %}
            <tr>
                <td>{{ document.filename }}</td>
                <td>{{ document._id }}</td>
                <td>
                    Статистика
                    Удалить
                </td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
    <p>В этой коллекции пока нет документов.</p>
    {% endif %}
    </body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>Document Analyzer|Upload</title>
    </head>
    <body>
        <h1>Document analyzer</h1>
        <nav>
            {% if not current_user.is_authenticated %}
            <h3>Добро пожаловать.</h3>
            <p>Пожалуйста, войдите или зарегестрируйтесь.</p>
            <a href="{{ url_for('auth_bp.login') }}">Авторизация</a>
            <a href="{{ url_for('auth_bp.register') }}">Регистрация</a>
            {% else %}
            <h3>Добро пожаловать, {{current_user.username}}</h3>
            <a href="{{ url_for('collections_bp.collections') }}">Мои коллекции</a>
            <a href="{{ url_for('api_user.logout') }}">Выход</a>
            {% endif %}
            
        </nav>
    </body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>Document Analyzer|Вход</title>
    </head>
    <body>
        <a href="{{ url_for('index_bp.index') }}">Домашняя страница</a>
        <form method="POST" action="{{ url_for('auth_bp.login') }}">
            <h2>Вход</h2>
            {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <h3>{{ message }}</h3>
                {% endfor %}
            {% endif %}
            {% endwith %}
            <input type="email" name="email" placeholder="Почта" required>
            <input type="password" name="password" placeholder="Пароль" required>
            <button type="submit">Войти</button>
            <div class="link">
            <a href="{{ url_for('auth_bp.register') }}">Нет аккаунта? Зарегистрируйся</a>
            </div>
            
        </form>
    </body>
</html>

app/templates/register.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>Document Analyzer|Вход</title>
    </head>
    <body>
        <a href="{{ url_for('index_bp.index') }}">Домашняя страница</a>
        <form method="POST" action="{{ url_for('auth_bp.register') }}">
            <h2>Регистрация</h2>
            {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <h3>{{ message }}</h3>
                {% endfor %}
            {% endif %}
            {% endwith %}
            <input type="text" name="username" placeholder="Имя пользователя" required>
            <input type="email" name="email" placeholder="Почта" required>
            <input type="password" name="password" placeholder="Пароль" required>
            <input type="password" name="password_repeat" placeholder="Повторите пароль" required>
            <button type="submit">Зарегистрироваться</button>
            <a href="{{ url_for('auth_bp.login') }}">Уже есть аккаунт? Войти</a>
        </form>
    </body>
</html>

app/templates/upload.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>Document Analyzer|Upload</title>
    </head>
    <body>
        <a href="{{ url_for('index_bp.index') }}">Домашняя страница</a>
        <a href="{{ url_for('collections_bp.collections') }}">Мои коллекции</a>
        <h1>Загрузить новый файл в коллекцию {{ collection_name }}</h1>
        <div id="loading" style="display: none;">Обработка документа...</div>
        <form method=post enctype=multipart/form-data onsubmit="showLoader()">
            <input type=file name=file>
            <input type=submit value=Upload>
        </form>
        {% if words %}
        <h2>Статистикадля {{ filename }}</h2>
        <table border="1">
            <tr>
                <th>Слово</th>
                <th>TF</th>
                <th>IDF</th>
            </tr>
            {% for row in words %}
            <tr>
                <td>{{ row.word }}</td>
                <td>{{ row.tf }}</td>
                <td>{{ row.idf }}</td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            {% endif %}
        {% endwith %}
        
        <script>
            function showLoader() {
                document.getElementById('loading').style.display = 'block';
            }
        </script>
    </body>
</html>